apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-prime-clone-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Manish636700/amazon-prime-clone-deploy.git
    targetRevision: main 
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-prime-clone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true