pipeline {
    agent any
    
    options {
        disableConcurrentBuilds()
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '20'))
        timeout(time: 30, unit: 'MINUTES')
        skipStagesAfterUnstable()
    }
    environment {
        AWS_REGION             = "us-east-1"
        ECR_REPO               = "amazon-prime-prod"
        IMAGE_TAG              = "${BUILD_NUMBER}"
        AWS_ACCESS_KEY_ID      = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY  = credentials('aws-secret-key')
        AWS_ACCOUNT_ID         = credentials('aws-account-id')
    }
    
      stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Manish636700/amazon-prime-clone-deploy.git'
            }
        }
        
       stage('Install Dependencies') {
         steps {
              sh 'npm ci'
          }
       }
     
      stage('Unit Tests & Coverage') {
         steps {
             sh 'npm test -- --coverage --passWithNoTests'
         }
      }
      
      stage('SonarQube Analysis') {
          environment {
              scannerHome     = tool 'sonar-scanner'
          }
          steps {
              withSonarQubeEnv('sonarqube') {
                  sh """
                   ${scannerHome}/bin/sonar-scanner \
                   -Dsonar.projectKey=amazon-prime-clone \
                   -Dsonar.sources=.\
                   -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
                  """
              }
          }
      }
      
      stage('Quality Gate (BLOCKING)') {
          steps {
              timeout(time: 10, unit: 'MINUTES') {
                  waitForQualityGate abortPipeline: true
              }
          }
      }
      
      stage('BUILD Application') {
          steps {
              sh ''' 
              echo "Build Application ...... "
              npm install
              npm run build || true
              '''
          }
      }
        stage('Dependency & Secret Scan') {
              steps {
                sh '''
                  trivy fs \
                  --scanners vuln \
                  --severity HIGH,CRITICAL \
                  --ignore-unfixed \
                  . || true
                '''
              }
            }

      stage('Docker Build (Non-Root Image)') {
          steps {
              sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
          }
      }
      
      stage('Container Image Scan') {
          steps {
            sh '''
              trivy image \
              $ECR_REPO:$IMAGE_TAG \
              --severity HIGH,CRITICAL || true
            '''
          }
        }
        
     stage('Login to AWS ECR') {
         steps {
             sh '''
              aws ecr get-login-password --region $AWS_REGION |
              docker login --username AWS \
              --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
             '''
         }
     }
     
     stage('Push Image to ECR (Non-Prod)') {
         steps {
             sh ''' 
              docker tag $ECR_REPO:$IMAGE_TAG \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
              
              docker push \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
              
             '''
             }
         }
      }
          post {
            success {
                echo "✅ CI completed successfully"
            }
            failure {
                echo "❌ Pipeline blocked by Quality/Security gate"
            }
            always {
                cleanWs()
            }
        }

}